### ISSUE TITLE
DGM - conditional independence or dependence?

### ISSUE THREAD

**Issue by andzuck** [harvard-ml-courses/cs181-textbook#5]
Chapter 8, page 109:

"In this setup, we say that information from A to C is being ‘blocked’ by the unobserved variable. B. Thus A and C are currently conditionally independent. However, once we’ve observed B, as shown in Figure 8.17, the information flow changes.
Now, information is flowing between A and C through the observed variable B, and thus A and C are now **conditionally independent**. This phenomenon, where the observation of the random variable in the middle creates conditional dependence is known as explaining away."

Should the bolded text be "conditionally dependent" instead of "conditionally independent"?

**Comment by elbertgong** [comment]
Thanks Andrew! Added a PR for it. https://github.com/harvard-ml-courses/cs181-textbook/pull/6

**Comment by jdhe1120** [comment]
fixed!
